/**
 * Vendors the web fonts into public/fonts/ so the app carries them itself.
 *
 * An offline dice roller cannot fetch its display face from Google when the
 * number flashes, and the reveal is the one piece of type in the app doing any
 * work. Fetching the stylesheet with a modern browser UA gets the woff2
 * subsets; only latin is kept, since nothing here renders text the user
 * supplies. Both families are variable fonts, so every weight Google lists is
 * the same file — they are stored once and the @font-face rules share it.
 *
 *   node tools/build-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const FAMILIES = [
  'Cormorant+Garamond:wght@300;500;600',
  'Inter:wght@400;500;600',
];
// Chrome asks for woff2; an old UA would be served ttf instead.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const outDir = path.resolve('public/fonts');
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const url = `https://fonts.googleapis.com/css2?family=${FAMILIES.join('&family=')}&display=swap`;
const css = await (await fetch(url, { headers: { 'user-agent': UA } })).text();

// css2 emits a run of `/* subset */ @font-face { ... }` blocks.
const blocks = css.split(/(?=\/\*\s*[a-z-]+\s*\*\/)/).filter((b) => b.includes('@font-face'));
const byHash = new Map();
const kept = [];

for (const block of blocks) {
  if (block.match(/\/\*\s*([a-z-]+)\s*\*\//)?.[1] !== 'latin') continue;

  const remote = block.match(/url\((https:[^)]+)\)/)?.[1];
  if (!remote) continue;
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';

  const data = Buffer.from(await (await fetch(remote, { headers: { 'user-agent': UA } })).arrayBuffer());
  const hash = crypto.createHash('sha256').update(data).digest('hex');
  let name = byHash.get(hash);
  if (!name) {
    name = `${family.toLowerCase().replace(/\s+/g, '-')}-latin.woff2`;
    fs.writeFileSync(path.join(outDir, name), data);
    byHash.set(hash, name);
    console.log(`  ${name}  ${(data.length / 1024).toFixed(1)} KB`);
  }
  console.log(`    ${family} ${weight} -> ${name}`);

  kept.push(block.replace(/url\(https:[^)]+\)/, `url(./${name})`).trim());
}

const header = `/* Generated by tools/build-fonts.mjs — do not edit.\n   Source: ${url}\n   Cormorant Garamond and Inter are licensed under the SIL Open Font License 1.1. */\n\n`;
fs.writeFileSync(path.join(outDir, 'fonts.css'), header + kept.join('\n\n') + '\n');

const bytes = [...byHash.values()].reduce((n, f) => n + fs.statSync(path.join(outDir, f)).size, 0);
console.log(`\n${kept.length} faces over ${byHash.size} files, ${(bytes / 1024).toFixed(0)} KB -> public/fonts/`);
